[package]
name = "toolkit-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "egui desktop application for win-toolkit"

[lints]
workspace = true

[[bin]]
name = "win-toolkit"
path = "src/main.rs"

[dependencies]
toolkit-core = { version = "=0.1.0", path = "../toolkit-core" }
toolkit-platform = { version = "=0.1.0", path = "../toolkit-platform" }
eframe.workspace = true
egui_extras.workspace = true
image.workspace = true
jiff.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
embed-resource = "=3.0.11"

[dev-dependencies]
tempfile.workspace = true

[package.metadata.cargo-machete]
ignored = ["embed-resource"]
